name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone oniux
      run: git clone --depth 1 --branch v0.6.0 https://gitlab.torproject.org/tpo/core/oniux.git

    - name: vendor stuff
      run: cd ./oniux && cargo vendor

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: archives-oniux
        path: ./oniux
        if-no-files-found: error
