name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone oniux
      run: git clone https://gitlab.torproject.org/tpo/core/oniux.git

    - name: vendor stuff
      run: cd ./oniux && cargo vendor

    - name: Archive .zip
      run: |
        tar cfvz oniux.tar.gz ./oniux

    - name: Upload Archive imperator
      uses: actions/upload-artifact@v4
      with:
        name: archives-oniux
        path: oniux.tar.gz
        if-no-files-found: error
