name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone oniux
      run: git clone https://gitlab.torproject.org/tpo/core/oniux.git

    - name: setup it as working directory
      working-directory: oniux
      run: cd oniux
      
    - name: ls
      run: ls
